### ISSUE TITLE
 Could not find artifact io.quarkus:quarkus-grpc-client:jar:1.0.1.Final 

### ISSUE THREAD

**Issue by gitmalong** [hpehl/quarkus-grpc-quickstart#2]
`mvn clean install`

`Failed to execute goal on project grpc-quickstart-client: Could not resolve dependencies for project io.grpc.examples.routeguide:grpc-quickstart-client:jar:1.0: Could not find artifact io.quarkus:quarkus-grpc-client:jar:1.0.1.Final in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by genericGenie** [comment]
Add the following dependency inside the "pom.xml" file within the **parent** and **client**, then perform the "mvn clean install" again.
```
<dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
      <version>1.27.2</version>
</dependency>
```
For some reason this fails in Eclipse, but works successfully in Intellij.  Yes, there are errors still floating around in the project; but it still works.

**Comment by swDevTX** [comment]
The suggested fix did not work. I continue to get the same error as gitmalong.  I'm not using Eclipse or Intellij at this point. I'm simply trying to build from the command line as indicated using "mvn clean install".

**Comment by genericGenie** [comment]
I also use IntelliJ.  Try this, open the command prompt or terminal and navigate to the parent directory.
Then navigate into the /proto directory, there should be pom.xml file in there.  Then use maven command: "mvn compile" or "mvn protobuf:compile".  That will tell the maven to use the ProtoBuf Maven plugin to open the *.proto file and generate the classes.  You may have to grant IntelliJ permissions to auto-import the dependencies, there is usually a mini-popup at the bottom right corner of the window; if you haven't enable it already.
Then navigate back to the parent directory, and run the "maven clean install"

**Comment by swDevTX** [comment]
I think you missed that I am NOT using IntelliJ or Eclipse.  I'm simply downloading the archive from the site and using maven from the command line as the instructions on the first page indicate.  The error is pretty clearly stating that the "io.grpc.examples.routeguide:grpc-quickstart-client:jar:1.0" is missing from the maven repository of third party libraries.  Understanding why this is, will help solve the problem.  I'm probably doing something dumb.  I'm working myself to figure it out.

**Comment by swDevTX** [comment]
As I suspected, I was doing something dumb.  The user must manually compile and self install the "quarkus-grpc-client-1.0.1.Final.jar" file to the maven repository just like the "quarkus-grpc" library.   

Unfortunately, I'm now getting a host of new compilation errors to go decipher.  :/

**Comment by hpehl** [comment]
Hi guys, sorry for the late response. Do you still have issues building the quickstart?
Quarkus 1.3.0.Final will be released soon and I'll update the gRPC projects.

**Comment by swDevTX** [comment]
As of today I'm still trying to figure out how to get it to compile.  While I am a experienced software developer I'm new to microservices, quarkus and gRPC.  (My industry lags about 3-5 years behind tech.)  So, I've probably not gotten something I need installed.  That said, the error I am working towards today is:

**First I see this...**
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[18,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[14,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/GetFeatureResource.java:[15,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[51,17] cannot find symbol
  symbol:   variable JsonFormat
  location: class io.grpc.examples.routeguide.RouteChatSocket
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[82,17] cannot find symbol
  symbol:   variable JsonFormat
  location: class io.grpc.examples.routeguide.RouteChatSocket.ResponseObserver
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[38,13] cannot find symbol
  symbol:   variable JsonFormat
  location: class io.grpc.examples.routeguide.ListFeaturesSocket
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[45,25] cannot find symbol
  symbol: variable JsonFormat
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/GetFeatureResource.java:[45,17] cannot find symbol
  symbol:   variable JsonFormat
  location: class io.grpc.examples.routeguide.GetFeatureResource


**Then this follows:**  (Presumably because of the compilation error)
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:compile (default-compile) on project grpc-quickstart-client: Compilation failure: Compilation failure:
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[18,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[14,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/GetFeatureResource.java:[15,32] package com.google.protobuf.util does not exist
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[51,17] cannot find symbol
[ERROR]   symbol:   variable JsonFormat
[ERROR]   location: class io.grpc.examples.routeguide.RouteChatSocket
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/RouteChatSocket.java:[82,17] cannot find symbol
[ERROR]   symbol:   variable JsonFormat
[ERROR]   location: class io.grpc.examples.routeguide.RouteChatSocket.ResponseObserver
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[38,13] cannot find symbol
[ERROR]   symbol:   variable JsonFormat
[ERROR]   location: class io.grpc.examples.routeguide.ListFeaturesSocket
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/ListFeaturesSocket.java:[45,25] cannot find symbol
[ERROR]   symbol: variable JsonFormat
[ERROR] /C:/project_files/microservices/quarkus-grpc-quickstart-master/client/src/main/java/io/grpc/examples/routeguide/GetFeatureResource.java:[45,17] cannot find symbol
[ERROR]   symbol:   variable JsonFormat
[ERROR]   location: class io.grpc.examples.routeguide.GetFeatureResource
[ERROR] -> [Help 1]

**Comment by hpehl** [comment]
Closing, since this extension is no longer supported. See README.md
